baseURL: https://lark-docs.pages.dev/
languageCode: en
title: Lark
theme: []
defaultContentLanguage: en

params:
  homepage: https://lark-docs.pages.dev
  description: The open-source docs platform that looks better than Mintlify.
  authors:
    - name: David Oladapo

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: colorful
  tableOfContents:
    startLevel: 2
    endLevel: 6

buildDrafts: true
buildFuture: true
enableRobotsTXT: true
disableKinds: ["404", "taxonomy", "RSS"]
